### ISSUE TITLE
[feature] Add regex matching with the audio device name

### ISSUE THREAD

**Issue by larspalo** [GrandOrgue/grandorgue#1265]
Since some time, at least dating back to commit 3a861221a252c4ec60aa93e1ce2c031c99cc1744 but could be older, the device id of USB audio devices seem to randomly change again at boots. This requires re-setting the audio device to get working sound again since wrong id is stored since last boot. A matching solution like that of the MIDI devices perhaps would be in order?

**Comment by oleg68** [comment]
@larspalo 

1 . Do you have several devices with the same `Physical name regex pattern` in their midi setup?
2. Are they plugged in an external usb hub or in the usb sockets on the motherboard?

**Comment by larspalo** [comment]
@oleg68 1. No, not normally anymore 2. Directly, or rather into a single usb interface by MIDI cables

However, I do need to do some additional careful testing to rule out that this was happening not only because I tend to use many different GO versions, that may not all be in sync with their versions, and that may have confused the settings (naming of the audio devices/ports). Anyway, the issue was with the audio device (also usb) that changed the port/id name, not really with the MIDI (but indeed the audio device also is MIDI capable and listed as an available MIDI device).

**Comment by larspalo** [comment]
@oleg68 Just to be clear, this is mainly an audio issue when it actually happens, I'm still trying to decide if it's really an issue or not...

This is the main issue:
![Skärmbild från 2022-11-22 21-13-08](https://user-images.githubusercontent.com/6173941/203421187-170177a4-5666-48c7-9a02-6b547ea7a97e.png)
That is: audio device is changed and not matching anymore
The new working settings would be:
![Skärmbild från 2022-11-22 21-13-37](https://user-images.githubusercontent.com/6173941/203421367-c05d024f-42fc-474c-80a8-1e5e217234c9.png)
And the MIDI settings would be:
![Skärmbild från 2022-11-22 21-13-54](https://user-images.githubusercontent.com/6173941/203421411-69131fe4-d487-43cc-9737-82b6264237c2.png)
At another reboot I could have a new working audio device port after a similar error as the first screenshot:
![Skärmbild från 2022-11-22 21-42-44](https://user-images.githubusercontent.com/6173941/203421741-b1cc2915-8791-4772-b9d7-0910bac97973.png)
And the new MIDI settings would be:
![Skärmbild från 2022-11-22 21-42-59](https://user-images.githubusercontent.com/6173941/203421885-45586db2-dba1-44b8-b6f5-304d5df01948.png)

But again, this is not happening regularly! It's random and I cannot be sure that it's not an issue with just my setup and computer/equipment startup procedure. I'll do some more testing over time and try to find out if this is really an issue or not! Just to be clear, I've not had any issues with the MIDI though as the ESI ports are used for GO input, the KeyRig is actually not really used with GO but more for note input in MuseScore...

**Comment by oleg68** [comment]
@larspalo GrandOrgue matchs the audio and midi devices by their names. Unfortunally, the names contain port numbers that could be changed across reboot. This changing occurs because the devices are initialised by the linux kernel in parallel, so thr race condition takes place, so it is a feature rather a bug.

The GrandOrgue midi interface allows users to set up a regex matching pattern for eliminating port numbers from matching. So it shouldn't be a problem with midi.

Unfortunally, there is no such capability in the audio interface. GrandOrgue tries to find a device with exactly the same name as it remember. So if the port number is included to the device name, GrandOrgue fails.

I note, that only PortAudio:alsa includes the port names into device names. RtAudio:alsa does not do that. So I'd suggest a workaround: use RtAudio instead of PortAudio.

May be to create a feature request: add a regex matching capability for audio device names as like as it already exists for midi device names, or to close this issue if the workaraund is acceptable for you?

**Comment by larspalo** [comment]
> May be to create a feature request: add a regex matching capability for audio device names as like as it already exists for midi device names, or to close this issue if the workaraund is acceptable for you?

@oleg68 That suggestion of audio device regex matching was what I hinted at in the starting post:

> A matching solution like that of the MIDI devices perhaps would be in order?

Anyway, this is not a critical issue in any way so there's no urgency about it. The reason for using PortAudio is that it will recognize the usb audio interface while RtAudio just won't (however there are workarounds for that too - like setting it as default device or using RtAudio Jack).

Bottom line is that yes, I think a regex matching for audio device names would be great but it's not the highest priority as there are ways around it for now!

**Comment by mattrixed** [comment]
Is there not a matching for audio devices already?  I have to use it all the time - with all of the changes and testing of late every time I uninstall the audio driver and try another one GO sees the same audio device plugged into the same socket as 2 then 3 then 4 etc... so i go into matching and change what all my settings are looking for winnm : focusrite audio 0  instead of what the system now reports as winnm: 1 focusrite audio 2 etc....
