### ISSUE TITLE
Separate MIDI events for Stop ON and Stop OFF

### ISSUE THREAD

**Issue by jrsorgan** [GrandOrgue/grandorgue#1392]
Stop control from an organ console appears to work only one way.  Stop can be activated with a midi B0 11 0F but will not turn off with B0 10 0F  Am I missing something in the setup or is this a current bug.
I am very new to GO and any help is appreciated.
Thank you

**Comment by larspalo** [comment]
Did you configure the MIDI send events?

**Comment by jrsorgan** [comment]
Midi stop control from the console is not configurable.  The stop tab sends a midi B0 10 0F to turn the stop on in GO.  The tab off sends a midi B0 11 0F which is not recognized by GO.

**Comment by larspalo** [comment]
Sounds like a complex midi detection might be needed instead of the normal simple event detection (done from the same right-click dialog). My midi message knowledge is a bit rusty, but the messages you cite seems to be referring to two different controllers.

**Comment by jrsorgan** [comment]
I have tried the complex midi detection process and that doesn't work either.  I loaded a demo of HW4.2 and it works fine but I prefer GO.  I did a quick search for this problem and it appears others are having the same problem.  Maybe one of the programmers will take a look and see if there is a bug.  Thanks for your suggestions.

**Comment by larspalo** [comment]
But GO recognizes both events, right? What if you add both events for the same stop (alternating)?

**Comment by jrsorgan** [comment]
Yes GO recognizes both events.  I'm not sure how to add 2 events for the same stop.  If you can point me in the right direction?\
J

**Comment by larspalo** [comment]
Just add one and then click the "New" button for the other.

**Comment by jrsorgan** [comment]
I tried your suggestion using Listen for Event and Detect complex MIDI setup.  I'm using MIDI Medic to send the stop on  B0 11 0F  and  stop off B0 10 0F  messages.  I can get the stop to turn on fine.  Can't get it to turn off.  The console is at church but I captured the tab on/off messages with MIDI-OX.  I will keep trying.

**Comment by jrsorgan** [comment]
I would appreciate it if someone could test my stop on, stop off problem.  So far most people have said that it will work.  I have been unable to get the stop off midi message to work.  I have tested at home using MIDI Medic to send the commands.  I have tested it at church with the console.  Stop on always works just fine.  Stop off does not.

**Comment by larspalo** [comment]
The message detected by the **simple** "Listen for event" will be Bx Controller. Since two different messages are sent you can configure two events that the stop in GO will listen for. I can easily get it to work simulating the stop on and off messages if I change the default Bx Controller event type to Bx Controller On/Off Alternating. Exactly how your console behaves might differ from the simulation I used, but by selecting an appropriate event type for each event you should have it working.

The setup steps that work for me:

1. Right click on the stop to be controlled in GO and hit simple listen for event button
2. Activate the console stop tab and GO should recognize it.
3. Click New (next to the event number drop down)
4. Again click simple listen for event button
5. De activate console stop tab and GO will recognize it as another event
6. In the drop down select the first event
7. Change event type from "Bx Controller" to "Bx Controller On/Off Alternating"
8. Select second event
9. Change event type as before in nbr 7
10. Click ok to close the dialog

Now any time I send either of the B0 11 0F and B0 10 0F the stop will change state. Hope that helps.

**Comment by larspalo** [comment]
@oleg68 As this seems to be more of a "helping with the usage" issue than anything wrong with GO, should this rather be moved to a discussion than an issue?

**Comment by oleg68** [comment]
@larspalo I need more research: I don't remenber, what is  B0 11 0F and  B0 1010F. But seems now GO does not allow to set up MIDI input events for Stop On and Stop Off separatelly. So I consider this issue as a feature request.

**Comment by jrsorgan** [comment]
Thank you for the "how to" step by step.  I have tested here and I will be going to the church next week to test with the console.

**Comment by jrsorgan** [comment]
Could the feature request be to enhance the "Detect complex MIDI setup" to accept in one step this kind of stop on/stop off MIDI data stream?
J

**Comment by larspalo** [comment]
@oleg68 As you know, almost any kind of MIDI messages can be used to trigger a stop on/off, but it must be setup correctly to also function properly, and that in itself may not be so obvious for a beginner in every situation. The messages sent in this case actually have different controller values (16 and 17 are detected in GO - from the MIDI standard I recon they are named "General Purpose Controller 1" and "General Purpose Controller 2"). This is quite different from say a Note On/Off message for the same note value, thus one need to configure the desired event(s) to an appropriate type in order to respond to the signals. I leave it totally up to you to research it, if you think the "Detect complex MIDI setup" could be improved so to setup the event(s) detection in a more automated way than what I did.

Just for general information to anyone interested: Most of the MIDI events types in GO have different alternatives - in this particular case "Bx Controller", "Bx Controller On", "Bx Controller Off" and "Bx Controller On/Off Alternating". Depending on the exact MIDI message sent, the right type of event must also be set so that GO knows what exactly to listen for - it's not always that the auto detected event type is the most appropriate for any given situation.

**Comment by oleg68** [comment]
@larspalo Now GO allows to set two different midi messages up, but they both will switch the stop state from it's current state to another.

The missing feature is to specify a message that is used only for enabling the stop and a message only for disabling the stop. They should not change the stop state if it is already in the target state.

**Comment by larspalo** [comment]
> The missing feature is to specify a message that is used only for enabling the stop and a message only for disabling the stop. They should not change the stop state if it is already in the target state.

Some events are specific for doing just that, and it's done very much by intention. Toggling on/off alternating is a prime example of that.

Normally the on/off state is connected (like in note on/off) in the same event which works fine for many cases, but not for every single one. Now the GO MIDI system is very flexible and allows for specifying many different events possible to listen for, but you're right that they doesn't say specifically which is on and which is off - _they just simply control the stop_ or button, or whatever object we're talking about.

If we require a separate configuration of the on and off state for every object, then it would usually be more work setting up the MIDI system for most users - it would be just the same as setting up two different events to listen to. It's certainly possible to do, but if possible I'd like the detection to still work as easily as it does now.

If you have ideas for achieving that, feel free to suggest and implement them. But to me, this is already working as it should.

**Comment by oleg68** [comment]
@larspalo I'd add a field `Used for` to the MIDI event dialog with three possible values: `On/Off` (by default), `On` or `Off`.

**Comment by larspalo** [comment]
@oleg68 Ok, that works for me.

**Comment by jrsorgan** [comment]
That would be a very nice enhancement.  Reversables and other momentary functions such as non-tunable traps that use non-typical midi messages could also be accommodated.  Thank you all for the analysis.

**Comment by larspalo** [comment]
@jrsorgan Try this: Look a little lower in the event list drop down. Choose the Bx Ctrl Change Fixed On/Off Value Alternating as event instead and then set the lower and upper limits to correspond to the values sent.

**Comment by larspalo** [comment]
@jrsorgan You should try experimenting with the different event types that have Bx fixed value and see if the On and Off states can be separated. If your console would have sent the same controller but different values for the on and off states the first Bx fixed value could perhaps have been used with separate On and Off values in a single event for stop control. Unfortunately it seems that your console sends same value but different controllers for the on and off states which I think requires setting up two events for each stop anyway.

**Comment by jrsorgan** [comment]
Your last suggestion seems to be working in the test.  Going to try it at the church tomorrow.  The remaining problem is the toggle.  If the same midi message, either off or on, is sent it toggles the stop.  I think you suggested a few posts ago an enhancement that would allow GO to accept a stop off midi command such as B2 10 09 as an exclusive stop off rather than a toggle.  Same goes for the stop on  B2 11 09.  This would work if the high and low limits are set for 9 and 9 so that no other stops are affected by the midi message.  I will report back on the success or ?? of the live test.

**Comment by jrsorgan** [comment]
This does work.  It eliminated any interference with other stops on GO.  I do think your idea for GO to use separate ON and OFF events to eliminate the possibility of a stop getting out of sync with the organ console is very good.  It looks like now that the Bx messages are all toggle.  Adding options for On and Off without the toggle could fix it.
