### ISSUE TITLE
Add a --justgui parameter for console panels development

### ISSUE THREAD

**Issue by rnditdev** [GrandOrgue/grandorgue#1602]
Hello everyone,

One common theme among samplesets developers is the difficulty of development of the graphic parts of a console. Could a --justgui flag or similar be developed, where GO just loads the panels (And probably shows a watermark indicating this mode)?
Ideally, when the program is in that mode, a function key reloads the whole GUI, or ideally, GO detects the file changes and reloads accordingly.

Best.

**Comment by rousseldenis** [comment]
@rnditdev Thanks for this suggestion.

Maybe --editmode could be a better wording.

However, you can maybe look at https://github.com/larspalo/GOODF development as even if I haven't tested yet, it suggests GUI helper is present in the tool.

@larspalo

**Comment by larspalo** [comment]
@rnditdev @rousseldenis With the latest versions it's now possible to display the actual panel layout in GOODF. Still it's necessary to set the parameters (x, y or row/col) for position control separately for the gui elements as they cannot (yet) be dragged on the panel to desired position.

I should also perhaps mention that GOODF is still very much in development and bugs are likely to exist...

**Comment by oleg68** [comment]
GrandOrgue is not intended to be a graphic console design tool.

@larspalo @rousseldenis should we move in this direction? Or it is better to suggest to use another tools like GOODF and OdfEdit for this?

**Comment by larspalo** [comment]
@oleg68 I think that external tools like GOODF or OdfEdit can handle both organ and graphical panel construction (odf) so that GrandOrgue can stay focused on the VPO rendering and playing experience. Also, it's already possible to set the global sample loading in GO to not load any samples if the user so desires.

**Comment by jefferycrowley** [comment]
I have created several GO ODF using new material and Old HW Sample sets.   I have also produced a full Hauptwerk.xml file, but this is a long and tedious task and all of the features of HW are not yet possible in GO.   Hauptwerk in early development promised a GUI to assist with compilation of graphic images to Hauptwerk.  It has never happened.   

 GO, on the other hand is easier to compile both the ODF and the GUI.   It would be awesome to have a tool that we can use, but it is not crucial to the development of GO.

 For GO, I use the free program of GIMP (I also have contributed monetarily to their effort).  I have found that being able to produce hi-resolution graphics with the actual size of the panels in GIMP while working on the .organ file works quite well.   I have tried to use Adobe Photoshop which works quite well but is prohibitively expensive even though I have used Cool Edit Pro/Adobe Audition for almost 20 years.   this alone is about $400.00 a year for a subscription and I also use Adobe Premier Pro for the production of organ videos and that is about $ 360.00 a year for the subscription.  Adding another Adobe product puts me in at over $1000.00 a month in usage fees.  I prefer Adobe Photoshop for only the graphic portion of the text because you can do amazing things with the text (for instance - using Bevel and Emboss on the text can make the visual Stops and console look very realistic.  But I can create original content with GIMP that surpasses Photoshop's abilities.   I have to work several months in addition, to edit the text of the stops and console to make them realistic.  A complete Sample Set with graphics can take me a year or more to produce (with original samples).   With GIMP you can create the Panels (as many as you desire) and place the elements on that panel AND GIMP has a tool to see the details of the placed file and included is the X and Y coordinates.   You can do this with a full-sized mock-up of the console.   Unfortunately one can not get a "report" from GIMP that puts the information in printed, readable form so that this can be done easily.   I am sure someone is gifted enough to compile a script for GIMP that would do this task.  I use a Libre Calculator file that is standardized between sample sets for all of this information.  It includes all of the 'states' of a graphic file (i.e. "on", "off" ) or a series of images for Expression control.  If I remember correctly jOrgan had an interface where you could drag and drop the image file into a Disposition, but I do not know how they accomplished this.

 So, although this is a tedious process any way you slice it - it also is a super helpful to view your images all together and working correctly.   And, yes, I have had to go back to the drawing board several times with each build to redesign the graphics to work correctly or to resize the images appropriately.  This way, by the time I am ready to complete the ODF, I can be assured that all of the images will fit and work correctly  the first time.

The only drawback to using GIMP is that when one exports a file to create a .png - I have to open the file again (in my case) with the Windows Photo editor to lighten the files up a bit and add more color because apparently even though I have set GIMP  to use RGB profile - that profile does not export the files with the correct RGB header - (Windows Photo Editor uses an Adobe RGB filter)  Otherwise the raw .png file will be almost unusable in Grand Orgue and very dark.  So that process takes about a week to complete properly.

I do agree that there should be some avenue to produce Grand Orgue Image Files in an ODF without loading the sound files and have the ability to either input X/Y cöordinates with each image from within This also, would be very time consuming and one cannot easily produce the graphic part of an ODF without a lot of time and effort.   An ODF "helper" would be welcome.
