### ISSUE TITLE
Context sensitive help shown modally

### ISSUE THREAD

**Issue by ahall41** [GrandOrgue/grandorgue#1661]
When selecting Help from a dialog, the Help window is shown modally, so you have to close it down, having not quite read everything, in order to change something. It should be shown non-modal (but, ideally only ever have one Help window open?).

**Comment by oleg68** [comment]
> It should be shown non-modal

It is not possible in linux because any modal windows cover any non-modal. See #1004

**Comment by ahall41** [comment]
I think #1004 is complaining that the Help window covers the dialogue? You can now click on the dialogue window - but you can't actually change anything until you close Help. Is this a "feature"?

**Comment by oleg68** [comment]
@ahall41 #1004 is complaining that the dialog window covers the help window. So the user cann't read the help.

> but you can't actually change anything until you close Help. Is this a "feature" (undesirable side effect) or 

It is a side effect of fixing #1004.

I agree that unability of usigng the dialog when the help window is open is not comode, but it is still better than the old behavior when the user could not read the help at all.

> can it be resolved?

No, it can not, because linux does not support visibility of not modal windows  while a modal window is shown.
