### ISSUE TITLE
Proper identification of GrandOrgue files in Cache and Data folders

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#700]
I am not able to decide wheter or not this could be considered as an issue or a nice-to-have request. For me is an issue so i post it here, not in the 'Pull Requests' section. 
At present, files in Cache and Data folders are stored with randomly generated names. This way, it is impossible to know which Organ a .cache or .cmb file belongs to. This leads to problems in cahce mgmt and generally speaking in settings update. I mean, i may need to delete entirely some organ, or just delete its cache, or simpy change its general settings; I could even be in the middle of changing pc or hard disk or simply moving directories to other personal folders. All these actions can be done easily in GO ; the problem is that it is not possible to know which files belong to which Organ.

**Comment by rousseldenis** [comment]
> I could even be in the middle of changing pc or hard disk or simply moving directories to other personal folders. All these actions can be done easily in GO ; the problem is that it is not possible to know which files belong to which Organ.

@paolo2504 If I understand, the feature you miss is the fact that knowing what cache file belongs to an organ in particular in order to copy a whole sample with configuration AND cache?

As already said, the cache management should be let to GrandOrgue discretion, but this is not the aim of your demand.

@GrandOrgue/administrators We can maybe improve the naming of cache files adding human-readable prefix or suffix ?

**Comment by rousseldenis** [comment]
> This is the wrong way to go. The cache and cmb files are not supposed to be edited by users by hand. Ever! As in never!
> 
> Whatever issue a user has that "require" changes done to these files should really be addressed elsewhere. It's up to GO to write and read those files. So, all the issues an user faces regarding these files should be fixed by changing how the user interacts with them from within GO.

That's what I said. The intent here is not modifying the content but the files naming template

**Comment by larspalo** [comment]
No, that's not the real purpose behind this request however veiled it might seem. The files themselves should "not" be identifiable, except through interaction from within GO. But it's very likely that the user interaction against them needs improvement! So, it's not the naming of the files that should be addressed but the interaction against them - updating, removing, possibly copying, making backups etc.

**Comment by rousseldenis** [comment]
> So, it's not the naming of the files that should be addressed but the interaction against them - updating, removing, possibly copying, making backups etc.

Oooh, ok, that's another way. That's indeed the wisdom's voice :smiley: your sight is far away from mine.

So, to summarize, it's more a 'Cache management' improvement more generally. It should deserve a proper development flow.

**Comment by paolo2504** [comment]
Let me try explain in another way. I want to be sure that when I remove an organ from Settings/Organs/delete selected… ALL related files are deleted: .cache and .cmb; the .idx file moist be update as well (not deleted , as I suppose it contains infos on other organs as well. 
definitely, as a user and as a developer I do want to know which file correspond to which organ. I don’t want to modify them of course.

**Comment by larspalo** [comment]
That's a valid point. We just have to find the best way to do that. In my opinion this issue should be fixed by improving the way the management is handled from within GO. There a user should be able to see what cache and cmb files exist and be able to "manage" them. There's no need to change the file naming so that the files will be easier identifiable from the folder tree manually - that only encourage the wrong type of initiatives.
