### ISSUE TITLE
[Feature Request] Banked Divisional Pistons (Ergo: A Traditional US/UK Combination Action System)

### ISSUE THREAD

**Issue by pgcrowe** [GrandOrgue/grandorgue#708]
The lack of banked **divisional** pistons is one of the greatest omissions on the GrandOrgue platform — one that past developers have refused to address. GrandOrgue's current combination action system is atypical to nearly every combination action in the US and UK. While one can compromise by making a banked **divisional** piston out of a banked **general** piston, the process is unintuitive, and leaves too few pistons left on a given memory level. Since code is already in place for banked **general** pistons, it couldn't be too difficult to add banked **divisional** pistons. It was on my GrandOrgue coding to-do list, but you can probably add it faster than I (while I commit the code for per-pipe release truncation).

**Comment by larspalo** [comment]
Well, this issue is not as trivial as it might seem.

GO can presently provide a completely **traditional** US/UK general/divisional combination system built in the panels. You have 50 generals and 10 divisionals (per division).

On top of this it's possible to re-purpose the 1000 free combinations (sequencer) existing (per .cmb file) using them as a "banked" version of generals - but in truth it's still the same 1000 free combinations existing in the background - only they are accessible in steps or "banks" possible to configure for the user at will. Also it's possible to use them in other ways, like pointed out above...

By the way, in a **really traditional** US/UK combination system you don't have banks, you just get what you see as pistons on the organ. It's only in more modern versions you have banks of generals and divisionals to overcome the obvious limitation of the old traditional system.

Anyway, while the banked generals could simply be a re-purposing of existing functionality it's not really the same with the divisionals since we have nothing to re-purpose there.

What we can do is of course to provide more than the current 10 divisionals each division, and provide a way to access them. However, the actual numbers of either divisionals or generals is not the same for every organ. While it's easy for us to say that in GO there could be a total of 100 divisionals in 10 banks of 10 each built in, in truth, most US/UK organs won't have that number of banks or pistons for each division - usually they are in some other number like 8, or anything really...

This makes me think that inside GO, if we at all want to expand on the number of divisionals, we should perhaps not at all assume a certain setup of banks/frames but just provide a larger number of total divisionals available and make the user responsible to map them to his console in whatever way it's working.

**Comment by oleg68** [comment]
@larspalo Would it be correct if switching the current bank of the genetal setter (±10, ±100) also switched the bank of all divisionals without changing the current combinations until some divisional would be pressed?

**Comment by larspalo** [comment]
I think that it would be best if the user could switch "bank" individually
for each division (independent of which "bank" another division is at).

But for the other part of the question, I do think that it should be a two
step process, one switching "bank" and two activating a divisional on that
new "bank ".

Den tors 15 sep. 2022 06:38Oleg Samarin ***@***.***> skrev:
