### ISSUE TITLE
ASIO: License agreement

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/grandorgue#822]
If you don't mind, I will send signed from me the ASIO license to Steinberg you can find here (in SDK zip file) https://www.steinberg.net/developers/

Drawback of this, I will be responsible of legal issues towards that (but I think there won't).

In another hand, depending on project evolutions, we can envisage a non-profit association creation that will protect us from those  kind of issues, but imply a little bit more constraints (but can help for funding, sponsoring etc...)

**Comment by oleg68** [comment]
@rousseldenis are we readuy to sign the license agreement?

**Comment by rousseldenis** [comment]
@oleg68 I have it ready. Waited just for your feedback on this to go forward.

**Comment by oleg68** [comment]
@rousseldenis May we continue without creation of the non-profit association?

**Comment by rousseldenis** [comment]
> @rousseldenis May we continue signing the ASIO agreement without creation of the non-profit association and without funding?

Of course. I wanted to tell the whole options. I will send it from me in the name of 'GrandOrgue' if it's ok for you? @larspalo

**Comment by oleg68** [comment]
I agree

**Comment by larspalo** [comment]
Sure, go ahead!

**Comment by wpostma** [comment]
Does this mean full ASIO support can come into binary builds again?

**Comment by rousseldenis** [comment]
> Does this mean full ASIO support can come into binary builds again?

This is already the case.

**Comment by wpostma** [comment]
I am not seeing ASIO in the list of options when I choose sound devices.  All the other non ASIO options do show up. Or does the ASIO option not show up with the four letters "ASIO" in the description when the software enumerates the available set of devices  + driver modes?

Speaking of availlable devices and driver modes having a flat list of [MODE1] x [DEVICE1] through [MODE8]x[DEVICE8] instead of TWO combo boxes, one for device driver type or category and the other for a device within that category is a really serious UI oversight, in my opinion.  It's like the model of the underlying audio engine was designed with two tiers of enumerable settings and the results of both are dumped into a single array of very complex strings, which make no sense to human beings.

I have extensive experience with DAWs and audio software and have never seen a wonkier representation.  For a future revision a change to the ui such that there is:

* A first combobox saying MME, WASAPI, ASIO, JACK, PIPEWIRE, DirectAudio, and whatever other types of drivers there are.
* A second combo box listing physical devices that are available under that "STEINBERG UR 44",  "USB AUDIO CODEC", "BEHRINGER MODEL 123".,

Would make GrandOrge much like other systems. The other funny thing is that of course setting up the outputs within the device should be automatically creating a stereo pair by default when adding, instead of making people figure out how to do that.   

I may be able to help with making this as easy to get started with as other audio applications, if help is wanted from someone with Win32 API experience.

**Comment by rousseldenis** [comment]
Forget this one. Done

**Comment by rousseldenis** [comment]
Received today the countersigned licensing from Steinberg
