### ISSUE TITLE
[Feature Request] Officially support "/" as path separator

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#827]
### Discussed in https://github.com/GrandOrgue/grandorgue/discussions/821

<div type='discussions-op-text'>

<sup>Originally posted by **vpoguru** October 31, 2021</sup>
The path separator "/" already works in all 3 operating systems, but GrandOrgue gives a warning (at least if "Perform strict ODF" is checked).

Linux and macOS terminals work with "/" anyway, and Windows supports this separator as well. If I remember correctly, the "/" separator could even be used (unofficially) in DOS times.</div>

**Comment by larspalo** [comment]
In july 2014 (regarding rev 1713) we had a short discussion about this. I thought basically the same thing as you, that we could use whichever path separator / or \ because wx will handle it correctly anyway but Martin was of another opinion. The help since old specifies \ as canonical separator and basic reason was complying to the HW1 standard.

I won't complain about removing the warning about which path separator is used, though.

PS. In DOS one would use / to specify parameters or switches to a program, never the paths, but this is very much irrelevant now.

**Comment by oleg68** [comment]
I propose to introduce a separate settings checkbox ``Check ODF for HW1 compatibility`` and print warnings about `/` delimiter only if is enabled.
